version: 1
rules:
  max-function-parameters:
    enabled: true
    max: 3
  source-file-header:
    required: true
    min-length: 60
    max-length: 0
  max-source-file-lines:
    max: 1000
  max-function-body-lines:
    max: 0
  function-docstring:
    policy: optional
languages:
  go:
    files:
      - cmd/debug/...
      - cmd/herm/...
      - prompts/...
      - tools/edit-file/...
      - tools/outline/...
      - tools/write-file/...
    exclude:
      - "**/*_test.go"
      - "**/testdata/**"
    rules:
      indent:
        type: language-default
        width: 0
      casing:
        enabled: false
        functions: language-default
        variables: language-default
        types: language-default
        constants: language-default
