// systemprompt.go builds the system prompt for the coding agent and sub-agents
// by rendering embedded Go templates with tool availability and project context.
package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"time"

	"herm/prompts"

	"langdag.com/langdag/types"
)

// PromptData holds all values passed to the system prompt templates.
type PromptData struct {
	HasBash        bool
	HostTools      []string // tool names that execute on the host (e.g. "git")
	HasDevenv      bool
	HasAgent       bool
	HasWebSearch   bool
	HasGlob        bool
	HasGrep        bool
	HasReadFile    bool
	HasOutline     bool
	HasEditFile    bool
	HasWriteFile   bool
	IsSubAgent     bool // true for sub-agent prompts: skips communication, personality, skills
	IsCPSL         bool // true when commands run in CPSL instead of a container
	ContainerImage string
	WorkDir        string
	WorktreeBranch string // current branch in the git worktree, if known
	Date           string
	Personality    string
	Skills         []Skill

	// Container environment manifest (from .herm/environment.md, generated by devenv build).
	ContainerEnv string

	// Project snapshot fields (populated at startup, injected into environment section).
	TopLevelListing string
	RecentCommits   string
	GitStatus       string

	// Tool iteration budget (injected dynamically via budgetReminderBlock).
	RemainingToolIterations int
	MaxToolIterations       int

	// DefaultSubAgentMaxTurns is the default turn budget for sub-agents.
	// Flows into templates so prompt text uses a single source of truth.
	DefaultSubAgentMaxTurns int
}

// buildSystemPromptOptions is the parameter bundle for buildSystemPrompt.
type buildSystemPromptOptions struct {
	tools          []Tool
	serverTools    []types.ToolDefinition
	skills         []Skill
	workDir        string
	personality    string
	containerImage string
	worktreeBranch string
	backend        backendKind
	snap           *projectSnapshot
}

// buildSystemPrompt constructs the system prompt for the coding agent.
// Tool-specific guidelines are included only when the corresponding tool is available.
// serverTools are provider-side tools (e.g. web search) declared but not executed by the client.
// Structured into: Environment, Role, Tools, Practices, Communication, Personality, Skills.
func buildSystemPrompt(opts buildSystemPromptOptions) string {
	toolNames := make(map[string]bool)
	var hostTools []string
	for _, t := range opts.tools {
		name := t.Definition().Name
		toolNames[name] = true
		if t.HostTool() {
			hostTools = append(hostTools, name)
		}
	}
	for _, st := range opts.serverTools {
		toolNames[st.Name] = true
	}

	isCPSL := opts.backend == backendCPSL
	data := PromptData{
		HasBash:                 toolNames["bash"],
		HostTools:               hostTools,
		HasDevenv:               toolNames["devenv"],
		HasAgent:                toolNames["agent"],
		HasWebSearch:            toolNames[types.ServerToolWebSearch],
		HasGlob:                 toolNames["glob"],
		HasGrep:                 toolNames["grep"],
		HasReadFile:             toolNames["read_file"],
		HasOutline:              toolNames["outline"],
		HasEditFile:             toolNames["edit_file"],
		HasWriteFile:            toolNames["write_file"],
		IsCPSL:                  isCPSL,
		ContainerImage:          opts.containerImage,
		WorkDir:                 promptWorkDir(opts.backend, opts.workDir),
		WorktreeBranch:          opts.worktreeBranch,
		Date:                    time.Now().Format("2006-01-02 15:04 MST"),
		Personality:             opts.personality,
		Skills:                  opts.skills,
		DefaultSubAgentMaxTurns: defaultGeneralMaxTurns,
	}

	if !isCPSL {
		data.ContainerEnv = readContainerEnv(opts.workDir)
	}

	if opts.snap != nil {
		data.TopLevelListing = opts.snap.TopLevel
		data.RecentCommits = opts.snap.RecentCommits
		data.GitStatus = opts.snap.GitStatus
	}

	var buf bytes.Buffer
	if err := prompts.Templates.ExecuteTemplate(&buf, "system", data); err != nil {
		// Templates are embedded and tested; a failure here is a bug.
		panic("systemprompt: " + err.Error())
	}
	return buf.String()
}

// readContainerEnv reads .herm/environment.md if it exists, falling back to
// the base image manifest. Returns each line prefixed by "- " for bullet
// rendering in the environment template.
func readContainerEnv(workDir string) string {
	raw := strings.TrimSpace(prompts.BaseEnvironment) // default to base image description
	if data, err := os.ReadFile(filepath.Join(workDir, ".herm", manifestFile)); err == nil {
		if trimmed := strings.TrimSpace(string(data)); trimmed != "" {
			raw = trimmed
		}
	}

	lines := strings.Split(raw, "\n")
	for i, l := range lines {
		lines[i] = "- " + l
	}
	return strings.Join(lines, "\n")
}

// buildSubAgentSystemPromptOptions is the parameter bundle for buildSubAgentSystemPrompt.
type buildSubAgentSystemPromptOptions struct {
	tools          []Tool
	serverTools    []types.ToolDefinition
	workDir        string
	containerImage string
	backend        backendKind
	snap           *projectSnapshot
}

// buildSubAgentSystemPrompt constructs a leaner system prompt for sub-agents.
// It uses the "system_subagent" entry-point template which chains only
// role, tools, practices, and environment — skipping communication,
// personality, and skills to reduce token overhead.
func buildSubAgentSystemPrompt(opts buildSubAgentSystemPromptOptions) string {
	toolNames := make(map[string]bool)
	var hostTools []string
	for _, t := range opts.tools {
		name := t.Definition().Name
		toolNames[name] = true
		if t.HostTool() {
			hostTools = append(hostTools, name)
		}
	}
	for _, st := range opts.serverTools {
		toolNames[st.Name] = true
	}

	isCPSL := opts.backend == backendCPSL
	containerEnv := ""
	if !isCPSL {
		containerEnv = readContainerEnv(opts.workDir)
	}

	data := PromptData{
		HasBash:                 toolNames["bash"],
		HostTools:               hostTools,
		HasDevenv:               toolNames["devenv"],
		HasAgent:                toolNames["agent"],
		HasWebSearch:            toolNames[types.ServerToolWebSearch],
		HasGlob:                 toolNames["glob"],
		HasGrep:                 toolNames["grep"],
		HasReadFile:             toolNames["read_file"],
		HasOutline:              toolNames["outline"],
		HasEditFile:             toolNames["edit_file"],
		HasWriteFile:            toolNames["write_file"],
		IsSubAgent:              true,
		IsCPSL:                  isCPSL,
		ContainerImage:          opts.containerImage,
		ContainerEnv:            containerEnv,
		WorkDir:                 promptWorkDir(opts.backend, opts.workDir),
		Date:                    time.Now().Format("2006-01-02 15:04 MST"),
		DefaultSubAgentMaxTurns: defaultGeneralMaxTurns,
		// Personality, Skills, WorktreeBranch intentionally omitted for sub-agents.
	}

	if opts.snap != nil {
		data.TopLevelListing = opts.snap.TopLevel
		data.RecentCommits = opts.snap.RecentCommits
		data.GitStatus = opts.snap.GitStatus
	}

	var buf bytes.Buffer
	if err := prompts.Templates.ExecuteTemplate(&buf, "system_subagent", data); err != nil {
		panic("systemprompt: " + err.Error())
	}
	return buf.String()
}

func promptWorkDir(backend backendKind, hostWorkDir string) string {
	if backend == backendCPSL {
		return cpslWorkerInitialCW
	}
	return hostWorkDir
}
