// systemprompt.go builds the system prompt for the main agent and sub-agents
// by rendering embedded Go templates with tool availability and project context.
package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"time"

	"herm/prompts"

	"langdag.com/langdag/types"
)

// PromptData holds all values passed to the system prompt templates.
type PromptData struct {
	HasBash            bool
	HostTools          []string // tool names that execute on the host (e.g. "git")
	HasDevenv          bool
	HasAgent           bool
	HasWebSearch       bool
	HasGlob            bool
	HasGrep            bool
	HasReadFile        bool
	HasOutline         bool
	HasEditFile        bool
	HasWriteFile       bool
	ContainerImage     string
	WorkDir            string
	WorktreeBranch     string // current branch in the git worktree, if known
	Date               string
	Personality        string
	Skills             []Skill
	WorkflowFirstStep  string
	ProjectOrientation string

	// Container environment manifest (from .herm/environment.md, generated by devenv build).
	ContainerEnv string

	// Project snapshot fields (populated at startup, injected into Project context).
	TopLevelListing       string
	RecentCommits         string
	GitStatus             string
	IsGitRepo             bool
	ProjectFilesLabel     string
	ProjectGitRepoLabel   string
	ProjectGitStatusLabel string

	// Tool iteration budget (injected dynamically via budgetReminderBlock).
	RemainingToolIterations int
	MaxToolIterations       int

	// DefaultSubAgentMaxTurns is the default turn budget for sub-agents.
	// Flows into templates so prompt text uses a single source of truth.
	DefaultSubAgentMaxTurns int
}

// buildSystemPromptOptions is the parameter bundle for buildSystemPrompt.
type buildSystemPromptOptions struct {
	tools          []Tool
	serverTools    []types.ToolDefinition
	skills         []Skill
	workDir        string
	personality    string
	containerImage string
	worktreeBranch string
	backend        backendKind
	snap           *projectSnapshot
}

// buildSystemPrompt constructs the system prompt for the main agent.
// Tool-specific guidelines are included only when the corresponding tool is available.
// serverTools are provider-side tools (e.g. web search) declared but not executed by the client.
// Structured into: Environment, Role, Tools, Practices, Communication, Personality, Skills.
func buildSystemPrompt(opts buildSystemPromptOptions) string {
	profile := promptProfileForBackend(opts.backend)
	data := newPromptData(newPromptDataOptions{
		tools:          opts.tools,
		serverTools:    opts.serverTools,
		workDir:        opts.workDir,
		containerImage: opts.containerImage,
		worktreeBranch: opts.worktreeBranch,
		personality:    opts.personality,
		skills:         opts.skills,
		profile:        profile,
	})

	if profile.includeContainerEnv {
		data.ContainerEnv = readContainerEnv(opts.workDir)
	}
	if opts.snap != nil {
		data.TopLevelListing = opts.snap.TopLevel
		data.RecentCommits = opts.snap.RecentCommits
		data.GitStatus = opts.snap.GitStatus
		data.IsGitRepo = opts.snap.IsGitRepo
	}
	return renderPromptTemplate(renderPromptTemplateOptions{name: profile.mainTemplate, data: data})
}

// readContainerEnv reads .herm/environment.md if it exists, falling back to
// the base image manifest. Returns each line prefixed by "- " for bullet
// rendering in the environment template.
func readContainerEnv(workDir string) string {
	raw := strings.TrimSpace(prompts.BaseEnvironment) // default to base image description
	if data, err := os.ReadFile(filepath.Join(workDir, ".herm", manifestFile)); err == nil {
		if trimmed := strings.TrimSpace(string(data)); trimmed != "" {
			raw = trimmed
		}
	}

	lines := strings.Split(raw, "\n")
	for i, l := range lines {
		lines[i] = "- " + l
	}
	return strings.Join(lines, "\n")
}

// buildSubAgentSystemPromptOptions is the parameter bundle for buildSubAgentSystemPrompt.
type buildSubAgentSystemPromptOptions struct {
	tools          []Tool
	serverTools    []types.ToolDefinition
	workDir        string
	containerImage string
	backend        backendKind
	snap           *projectSnapshot
}

// buildSubAgentSystemPrompt constructs a leaner system prompt for sub-agents
// from the selected backend profile. It skips communication, personality, and
// skills to reduce token overhead.
func buildSubAgentSystemPrompt(opts buildSubAgentSystemPromptOptions) string {
	profile := promptProfileForBackend(opts.backend)
	data := newPromptData(newPromptDataOptions{
		tools:          opts.tools,
		serverTools:    opts.serverTools,
		workDir:        opts.workDir,
		containerImage: opts.containerImage,
		profile:        profile,
	})
	if profile.includeContainerEnv {
		data.ContainerEnv = readContainerEnv(opts.workDir)
	}
	if opts.snap != nil {
		data.TopLevelListing = opts.snap.TopLevel
		data.RecentCommits = opts.snap.RecentCommits
		data.GitStatus = opts.snap.GitStatus
		data.IsGitRepo = opts.snap.IsGitRepo
	}
	return renderPromptTemplate(renderPromptTemplateOptions{name: profile.subAgentTemplate, data: data})
}

type newPromptDataOptions struct {
	tools          []Tool
	serverTools    []types.ToolDefinition
	workDir        string
	containerImage string
	worktreeBranch string
	personality    string
	skills         []Skill
	profile        backendPromptProfile
}

func newPromptData(opts newPromptDataOptions) PromptData {
	toolNames := make(map[string]bool)
	var hostTools []string
	for _, t := range opts.tools {
		name := t.Definition().Name
		toolNames[name] = true
		if t.HostTool() {
			hostTools = append(hostTools, name)
		}
	}
	for _, st := range opts.serverTools {
		toolNames[st.Name] = true
	}

	return PromptData{
		HasBash:                 toolNames[toolBash],
		HostTools:               hostTools,
		HasDevenv:               toolNames["devenv"],
		HasAgent:                toolNames["agent"],
		HasWebSearch:            toolNames[types.ServerToolWebSearch],
		HasGlob:                 toolNames["glob"],
		HasGrep:                 toolNames["grep"],
		HasReadFile:             toolNames["read_file"],
		HasOutline:              toolNames["outline"],
		HasEditFile:             toolNames["edit_file"],
		HasWriteFile:            toolNames["write_file"],
		ContainerImage:          opts.containerImage,
		WorkDir:                 opts.profile.workDir(opts.workDir),
		WorktreeBranch:          opts.worktreeBranch,
		Date:                    time.Now().Format("2006-01-02 15:04 MST"),
		Personality:             opts.personality,
		Skills:                  opts.skills,
		WorkflowFirstStep:       opts.profile.workflowFirstStep,
		ProjectOrientation:      opts.profile.projectOrientation,
		ProjectFilesLabel:       opts.profile.projectFilesLabel,
		ProjectGitRepoLabel:     opts.profile.projectGitRepoLabel,
		ProjectGitStatusLabel:   opts.profile.projectGitStatusLabel,
		DefaultSubAgentMaxTurns: defaultGeneralMaxTurns,
	}
}

type renderPromptTemplateOptions struct {
	name string
	data PromptData
}

func renderPromptTemplate(opts renderPromptTemplateOptions) string {
	var buf bytes.Buffer
	if err := prompts.Templates.ExecuteTemplate(&buf, opts.name, opts.data); err != nil {
		// Templates are embedded and tested; a failure here is a bug.
		panic("systemprompt: " + err.Error())
	}
	return buf.String()
}
