import Foundation

func parseEnv(_ text: String) -> [String: String] {
    var values: [String: String] = [:]
    for rawLine in text.split(whereSeparator: \.isNewline) {
        let line = rawLine.trimmingCharacters(in: .whitespaces)
        guard !line.isEmpty, !line.hasPrefix("#") else {
            continue
        }

        let assignment = line.hasPrefix("export ") ? String(line.dropFirst("export ".count)) : line
        guard let separator = assignment.firstIndex(of: "=") else {
            continue
        }

        let key = assignment[..<separator].trimmingCharacters(in: .whitespaces)
        guard !key.isEmpty else {
            continue
        }

        var value = trimmedEnvValue(assignment[assignment.index(after: separator)...])
        if value.count >= 2,
           let first = value.first,
           let last = value.last,
           (first == "\"" && last == "\"") || (first == "'" && last == "'") {
            value.removeFirst()
            value.removeLast()
        }
        values[key] = value
    }
    return values
}

private func trimmedEnvValue(_ rawValue: Substring) -> String {
    var value = ""
    var previousWasWhitespace = true
    var isInsideSingleQuotes = false
    var isInsideDoubleQuotes = false

    for character in rawValue {
        if character == "'", !isInsideDoubleQuotes {
            isInsideSingleQuotes.toggle()
        } else if character == "\"", !isInsideSingleQuotes {
            isInsideDoubleQuotes.toggle()
        } else if character == "#",
                  previousWasWhitespace,
                  !isInsideSingleQuotes,
                  !isInsideDoubleQuotes {
            break
        }

        value.append(character)
        previousWasWhitespace = character.isWhitespace
    }

    return value.trimmingCharacters(in: .whitespaces)
}

private func swiftStringLiteral(_ value: String) -> String {
    var literal = "\""
    for scalar in value.unicodeScalars {
        switch scalar {
        case "\"":
            literal += "\\\""
        case "\\":
            literal += "\\\\"
        case "\n":
            literal += "\\n"
        case "\r":
            literal += "\\r"
        case "\t":
            literal += "\\t"
        default:
            if scalar.value >= 0x20 && scalar.value <= 0x7E {
                literal.unicodeScalars.append(scalar)
            } else {
                literal += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
            }
        }
    }
    literal += "\""
    return literal
}

private func generatedSource(values: [String: String]) -> String {
    var lines = [
        "// Generated by scripts/generate-apple-env-constants.sh.",
        "// Do not edit or commit this file.",
        "",
        "nonisolated enum CPSLEnvConstants {",
        "    static let values: [String: String] = ["
    ]

    for key in values.keys.sorted() {
        guard let value = values[key] else {
            continue
        }
        lines.append("        \(swiftStringLiteral(key)): \(swiftStringLiteral(value)),")
    }

    lines.append(contentsOf: [
        "    ]",
        "}",
        ""
    ])
    return lines.joined(separator: "\n")
}

let arguments = Array(CommandLine.arguments.dropFirst())
guard let outputPath = arguments.first else {
    fputs("usage: generate-apple-env-constants.swift OUTPUT [ENV_FILE...]\n", stderr)
    exit(64)
}

var values: [String: String] = [:]
for path in arguments.dropFirst() {
    guard FileManager.default.fileExists(atPath: path) else {
        continue
    }
    let url = URL(fileURLWithPath: path)
    let text = try String(contentsOf: url, encoding: .utf8)
    parseEnv(text).forEach { key, value in
        values[key] = value
    }
}

let outputURL = URL(fileURLWithPath: outputPath)
try FileManager.default.createDirectory(
    at: outputURL.deletingLastPathComponent(),
    withIntermediateDirectories: true
)
try generatedSource(values: values).write(to: outputURL, atomically: true, encoding: .utf8)
