#!/usr/bin/env bash
# Generate app/apple/herm/Generated/CPSLPCCRuntime.generated.swift
#
# Full runtime (PrivateCloudComputeLanguageModel) is only emitted when the active
# SDK is 27+ (or HERM_FORCE_PCC_RUNTIME=1). Older SDKs get a stub so the app
# still typechecks on the project's 26.5 deployment toolchain.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
apple_root="${SRCROOT:-"$repo_root/app/apple"}"
output="${APPLE_PCC_RUNTIME_OUTPUT:-"$apple_root/herm/Generated/CPSLPCCRuntime.generated.swift"}"
full_src="$repo_root/scripts/apple-pcc/CPSLPCCRuntime.full.swift"
stub_src="$repo_root/scripts/apple-pcc/CPSLPCCRuntime.stub.swift"

sdk_has_pcc() {
  if [[ "${HERM_FORCE_PCC_RUNTIME:-}" == "1" ]]; then
    return 0
  fi
  if [[ "${HERM_FORCE_PCC_RUNTIME:-}" == "0" ]]; then
    return 1
  fi

  local ver="${SDK_VERSION:-}"
  if [[ -z "$ver" ]] && command -v xcrun >/dev/null 2>&1; then
    ver="$(xcrun --sdk "${SDK_NAME:-macosx}" --show-sdk-version 2>/dev/null || true)"
  fi
  local major="${ver%%.*}"
  if [[ "$major" =~ ^[0-9]+$ ]] && ((10#$major >= 27)); then
    return 0
  fi

  # Content probe when version is missing/ambiguous but SDKROOT points at a 27+ SDK.
  if [[ -n "${SDKROOT:-}" && -d "${SDKROOT}" ]]; then
    if grep -R --include='*.swiftinterface' -l 'PrivateCloudComputeLanguageModel' \
      "${SDKROOT}" 2>/dev/null | head -n 1 | grep -q .; then
      return 0
    fi
  fi
  return 1
}

mkdir -p "$(dirname "$output")"

header="// Auto-generated by scripts/generate-apple-pcc-runtime.sh — do not edit.
// Source of truth: scripts/apple-pcc/CPSLPCCRuntime.{full,stub}.swift
"

if sdk_has_pcc; then
  {
    printf '%s\n' "$header"
    printf '// Variant: full (SDK provides PrivateCloudComputeLanguageModel)\n\n'
    cat "$full_src"
  } >"$output"
  echo "generated PCC runtime (full): $output"
else
  {
    printf '%s\n' "$header"
    printf '// Variant: stub (SDK lacks PrivateCloudComputeLanguageModel)\n\n'
    cat "$stub_src"
  } >"$output"
  echo "generated PCC runtime (stub): $output"
fi
